# --- C1 Container --- 
Container_C1_Relative = Frame(window)
Container_C1_Relative.pack(side="top")

# Row Containers
Container_C1_Row1 = Frame(Container_C1_Relative)
Container_C1_Row2 = Frame(Container_C1_Relative)
Container_C1_Row3 = Frame(Container_C1_Relative)
Container_C1_Row1.pack()
Container_C1_Row2.pack()
Container_C1_Row3.pack()

ButtonC11 = Entry(Container_C1_Row1, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC12 = Entry(Container_C1_Row1, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC13 = Entry(Container_C1_Row1, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC14 = Entry(Container_C1_Row2, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC15 = Entry(Container_C1_Row2, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC16 = Entry(Container_C1_Row2, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC17 = Entry(Container_C1_Row3, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC18 = Entry(Container_C1_Row3, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
ButtonC19 = Entry(Container_C1_Row3, fg=font_color, background="#c4c4c4", font=(font_familly, font_size), width=entry_width, border=0, justify="center")
switch(C1[1], COL1[1], ButtonC11)
switch(C1[2], COL1[1], ButtonC12)
switch(C1[3], COL1[1], ButtonC13)
switch(C1[4], COL1[1], ButtonC14)
switch(C1[5], COL1[1], ButtonC15)
switch(C1[6], COL1[1], ButtonC16)
switch(C1[7], COL1[1], ButtonC17)
switch(C1[8], COL1[1], ButtonC18)
switch(C1[9], COL1[1], ButtonC19)
ButtonC11.pack(side="left")
ButtonC12.pack(side="left")
ButtonC13.pack(side="left")
ButtonC14.pack(side="left")
ButtonC15.pack(side="left")
ButtonC16.pack(side="left")
ButtonC17.pack(side="left")
ButtonC18.pack(side="left")
ButtonC19.pack(side="left")
